# Generated by Django 4.0.2 on 2022-02-22 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 22, 12, 9, 34, 256939, tzinfo=utc), verbose_name=datetime.datetime(2022, 2, 22, 12, 9, 34, 255468, tzinfo=utc)),
        ),
    ]
