# Generated by Django 4.0.2 on 2022-02-22 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 2, 22, 12, 10, 49, 591987, tzinfo=utc)),
        ),
    ]
