# Generated by Django 4.0.2 on 2022-02-23 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_category_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 23, 6, 38, 22, 168343, tzinfo=utc)),
        ),
    ]
