# Generated by Django 4.0.2 on 2022-02-23 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 23, 6, 58, 23, 888325, tzinfo=utc)),
        ),
    ]
